rm(list=ls())
data <- fread("~/OneDrive/Documents/Coursera/DataScience/EDA/data/household_power_consumption.txt", header=TRUE, sep = ";", na.strings=c("?"), data.table=FALSE)
data$Date2 <- as.Date(data$Date, format = "%d/%m/%Y")
data <-subset(data, Date2 >= "2007-02-01" & Date2 <= "2007-02-02")
data$Time <- paste(data$Date, data$Time)
data$Time2 <- strptime(data$Time, format = "%d/%m/%Y %H:%M:%S")
png(file="plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(data$Time2,data$Global_active_power, type = "l", ylab ="Global Active Power (kilowatts)", xlab ="")
plot(data$Time2,as.numeric(data$Voltage), type = "l", ylab ="Voltage", xlab ="datetime")
plot(data$Time2,data$Sub_metering_1, type = "l", ylab ="Energy sub metering", xlab ="")
lines(data$Time2,data$Sub_metering_2, type = "l", col="red")
lines(data$Time2,data$Sub_metering_3, type = "l", col="blue")
legend("topright", bty="n", lwd=1, col=c("black", "red","blue"), legend=c("Sub_meetering_1", "Sub_meetering_2","Sub_meetering_3"),box.lwd=0)
plot(data$Time2,as.numeric(data$Global_reactive_power), type = "l", ylab ="Global_reactive_power", xlab ="datetime")
dev.off() 
