rm(list=ls())
data <- fread("~/OneDrive/Documents/Coursera/DataScience/EDA/data/household_power_consumption.txt", header=TRUE, sep = ";", na.strings=c("?"), data.table=FALSE)
data$Date2 <- as.Date(data$Date, format = "%d/%m/%Y")
data <-subset(data, Date2 >= "2007-02-01" & Date2 <= "2007-02-02")
data$Time <- paste(data$Date, data$Time)
data$Time2 <- strptime(data$Time, format = "%d/%m/%Y %H:%M:%S")
png(file="plot2.png", width = 480, height = 480)
plot(data$Time2,data$Global_active_power, type = "l", ylab ="Global Active Power (kilowatts)", xlab ="")
dev.off()